name: Deploy HuggingFace Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git clone https://user:$HF_ACCESS_TOKEN@https://huggingface.co/spaces/abhijitpadhi1/Transaction-Tracking space

          rsync -av --exclude space --exclude .git . space/

          cd space

          git add .
          git commit -m "Auto deploy from GitHub"
          git push